-- BORRAMOS LA BASE DE DATOS SOLO SI YA EXISTE PREVIAMENTE
drop database if EXISTS PROYECTO_RESERVAS;

-- CREAMOS LA BASE DE DATOS
create database PROYECTO_RESERVAS;

use PROYECTO_RESERVAS;

-- CREAMOS LA TABLA SOCIOS
create table SOCIOS (
	ID_SOCIO INT primary key AUTO_INCREMENT 
,	NOMBRE VARCHAR (50)
,	APELLIDO VARCHAR (50)
,	DNI INT unique 
,	TELEFONO INT not NULL
,	MAIL VARCHAR (60) not null unique 
,	FECHA_ALTA datetime
);

-- CREAMOS LA TABLA RESERVAS
create table RESERVAS(
	ID_RESERVA int primary key auto_increment
,	FECHA_HORA datetime
,	CANCELACION DATETIME
,	ID_SOCIO int 
,	ID_ACTIVIDAD int
,	ID_PROFESOR int
,	ID_SEDE int
);

-- CREAMOS LA TABLA ACTIVIDADES
create table ACTIVIDADES (
	ID_ACTIVIDAD int unique primary key
,	NOMBRE varchar (50)
,	DISPONIBILIDAD boolean
, 	FECHA_HORA DATETIME
,	ID_PROFESOR int
);

-- CREAMOS LA TABLA SEDE
create table SEDE (
	ID_SEDE INT primary key AUTO_INCREMENT
,	DIRECCION VARCHAR (100)
,	TELEFONO INT 
,	ID_DUENO INT
);

-- CREAMOS LA TABLA DUEÑO
create table DUENO (
	ID_DUENO INT primary key AUTO_INCREMENT
,	NOMBRE VARCHAR (50)
,	APELLIDO VARCHAR (50)
,	TELEFONO INT not NULL
);

-- CREAMOS LA TABLA PROFESORES
create table PROFESORES (
	ID_PROFESOR INT unique primary key auto_increment 
,	NOMBRES VARCHAR (50)
,   APELLIDO VARCHAR (50)
,	DNI INT unique
,	TELEFONO int
,	ALTA datetime
,	ID_ACTIVIDAD INT
,	ID_SEDE int
);


-- DEFINIMOS LAS FOREIGN KEYS DE CADA UNA DE LAS TABLAS

-- TABLA RESERVAS

ALTER TABLE RESERVAS
    ADD CONSTRAINT FK_RESERVAS_SOCIO
    FOREIGN KEY (ID_SOCIO) REFERENCES SOCIOS(ID_SOCIO);

ALTER TABLE RESERVAS
    ADD CONSTRAINT FK_RESERVAS_ACTIVIDAD
    FOREIGN KEY (ID_ACTIVIDAD) REFERENCES ACTIVIDADES(ID_ACTIVIDAD);
    
ALTER TABLE RESERVAS
    ADD CONSTRAINT FK_RESERVAS_PROFESOR
    FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESORES(ID_PROFESOR);
    
ALTER TABLE RESERVAS
    ADD CONSTRAINT FK_RESERVAS_SEDE
    FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID_SEDE);

-- TABLA DUENO

ALTER TABLE SEDE
	ADD CONSTRAINT FK_SEDE_DUENO
    FOREIGN KEY (ID_DUENO) REFERENCES DUENO(ID_DUENO);

-- TABLA PROFESORES

ALTER TABLE PROFESORES
    ADD CONSTRAINT FK_PROFESOR_ACTIVIDAD
    FOREIGN KEY (ID_ACTIVIDAD) REFERENCES ACTIVIDADES(ID_ACTIVIDAD);
    
ALTER TABLE PROFESORES
    ADD CONSTRAINT FK_PROFESOR_SEDE
    FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID_SEDE);

-- TABLA ACTIVIDADES

ALTER TABLE ACTIVIDADES
    ADD CONSTRAINT FK_ACTIVIDAD_PROFESOR
    FOREIGN KEY (ID_PROFESOR) REFERENCES PROFESORES(ID_PROFESOR);
    

-- SHOW tables FROM proyecto_reservas;




